### ISSUE TITLE
Failed to open Rowdy settings

### ISSUE THREAD

**Issue by Luna712** [rushi-chavan/rowdy-cs-extensions#1]
Extension: v18
Cloudstream: 4.3.2 0a5399d

Logcat:
```
--------- beginning of main
InputMethodManager: invalidateInput
05-07 11:47:09.663 26915 26915 I PLG     : updatePluginList = https://raw.githubusercontent.com/rushi-chavan/rowdy-cs-extensions/builds/repo.json
05-07 11:47:09.663 26915 26915 I PLG     : getPlugins = https://raw.githubusercontent.com/rushi-chavan/rowdy-cs-extensions/builds/repo.json
05-07 11:47:10.420 26915 26915 I ViewRootImpl@52b934d[MainActivity]: ViewPostIme pointer 0
05-07 11:47:10.501 26915 26915 I ViewRootImpl@52b934d[MainActivity]: ViewPostIme pointer 1
05-07 11:47:10.508 26915 26915 E PluginAdapter: Failed to open Rowdy settings: java.lang.IllegalStateException: FragmentManager has been destroyed
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1666)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:507)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at com.RowdyAvocado.RowdyPlugin$load$1.invoke(RowdyPlugin.kt:98)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at com.RowdyAvocado.RowdyPlugin$load$1.invoke(RowdyPlugin.kt:96)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at com.lagradost.cloudstream3.ui.settings.extensions.PluginAdapter$PluginViewHolder.bind$lambda$2(PluginAdapter.kt:183)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at com.lagradost.cloudstream3.ui.settings.extensions.PluginAdapter$PluginViewHolder.$r8$lambda$MgXwCFOV-rzXLmRv7XJuNDam_JE(Unknown Source:0)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at com.lagradost.cloudstream3.ui.settings.extensions.PluginAdapter$PluginViewHolder$$ExternalSyntheticLambda2.onClick(Unknown Source:6)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at android.view.View.performClick(View.java:8043)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at android.view.View.performClickInternal(View.java:8020)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at android.view.View$PerformClick.run(View.java:31850)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at android.os.Handler.handleCallback(Handler.java:958)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at android.os.Looper.loopOnce(Looper.java:230)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at android.os.Looper.loop(Looper.java:319)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at android.app.ActivityThread.main(ActivityThread.java:8893)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at java.lang.reflect.Method.invoke(Native Method)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
05-07 11:47:10.508 26915 26915 E PluginAdapter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
05-07 11:47:11.975 26915 26915 I ViewRootImpl@52b934d[MainActivity]: ViewPostIme pointer 0
05-07 11:47:12.042 26915 26915 I ViewRootImpl@52b934d[MainActivity]: ViewPostIme pointer 1
05-07 11:47:12.064 26915 26915 I Dialog  : mIsDeviceDefault = false, mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
05-07 11:47:12.098 26915 26915 I DecorView: setWindowBackground: isPopOver=false color=0 d=android.graphics.drawable.ColorDrawable@bba4fab
05-07 11:47:12.103 26915 28577 D NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
05-07 11:47:12.112 26915 26915 D InsetsController: onStateChanged: host=com.lagradost.cloudstream3.prerelease/com.lagradost.cloudstream3.MainActivity from=android.view.ViewRootImpl.setView:1717 state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2316), mDisplayCutout=DisplayCutout{insets=Rect(0, 75 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(512, 0 - 568, 75), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2316 physicalDisplayWidth=1080 physicalDisplayHeight=2316 density={2.8125} cutoutSpec={M 0,0 H -10 V 26.66666666666667 H 10 V 0 H 0 Z @dp} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=8, center=Point(8, 8)}, RoundedCorner{position=TopRight, radius=8, center=Point(1072, 8)}, RoundedCorner{position=BottomRight, radius=8, center=Point(1072, 2308)}, RoundedCorner{position=BottomLeft, radius=8, center=Point(8, 2308)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2316), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(956, 0 - 1080, 75) rotation=0}, mDisplayShape=DisplayShape{ spec=1667685767 displayWidth=1440 displayHeight=3088 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {a1a30001 mType=navigationBars mFrame=[0,2181][1080,2316] mVisible=true mFlags=[]}, InsetsSource: {a1a30004 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {a1a30005 mType=mandatorySystemGestures mFrame=[0,2181][1080,2316] mVisible=true mFlags=[]}, InsetsSource: {a1a30006 mType=tappableElement mFrame=[0,2181][1080,2316] mVisible=true mFlags=[]}, InsetsSource: {a1a30024 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {3 mType=ime mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {27 mType=displayCutout mFrame=[0,0][1080,75] mVisible=true mFlags=[]}, InsetsSource: {70410000 mType=statusBars mFrame=[0,0][1080,75] mVisible=true mFlags=[]}, InsetsSource: {70410005 mType=mandatorySystemGestures mFrame=[0,0][1080,109] mVisible=true mFlags=[]}, InsetsSource: {70410006 mType=tappableElement mFrame=[0,0][1080,75] mVisible=true mFlags=[]} }
05-07 11:47:12.112 26915 26915 I ViewRootImpl@16a1d05[MainActivity]: synced displayState. AttachInfo displayState=2
05-07 11:47:12.114 26915 26915 I ViewRootImpl@16a1d05[MainActivity]: setView = com.android.internal.policy.DecorView@fcb5868 TM=true
05-07 11:47:12.125 26915 26915 D InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=true, type=1
05-07 11:47:12.125 26915 26915 D InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=true, type=2
05-07 11:47:12.128 26915 26915 I BLASTBufferQueue_Java: new BLASTBufferQueue, mName= ViewRootImpl@16a1d05[MainActivity] mNativeObject= 0xb400007a24990070 sc.mNativeObject= 0xb400007a1498aed0 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2979 android.view.ViewRootImpl.relayoutWindow:9998 android.view.ViewRootImpl.performTraversals:4056 android.view.ViewRootImpl.doTraversal:3239 android.view.ViewRootImpl$TraversalRunnable.run:11197 android.view.Choreographer$CallbackRecord.run:1650 android.view.Choreographer$CallbackRecord.run:1659 android.view.Choreographer.doCallbacks:1129 android.view.Choreographer.doFrame:1055 android.view.Choreographer$FrameDisplayEventReceiver.run:1622 
05-07 11:47:12.128 26915 26915 I BLASTBufferQueue_Java: update, w= 1080 h= 2316 mName = ViewRootImpl@16a1d05[MainActivity] mNativeObject= 0xb400007a24990070 sc.mNativeObject= 0xb400007a1498aed0 format= -2 caller= android.graphics.BLASTBufferQueue.<init>:89 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2979 android.view.ViewRootImpl.relayoutWindow:9998 android.view.ViewRootImpl.performTraversals:4056 android.view.ViewRootImpl.doTraversal:3239 android.view.ViewRootImpl$TraversalRunnable.run:11197 
05-07 11:47:12.128 26915 26915 I ViewRootImpl@16a1d05[MainActivity]: Relayout returned: old=(0,0,1080,2316) new=(0,0,1080,2316) req=(1080,2316)0 dur=7 res=0x403 s={true 0xb400007bb49d1930} ch=true seqId=0
05-07 11:47:12.128 26915 26915 I ViewRootImpl@16a1d05[MainActivity]: performConfigurationChange setNightDimText nightDimLevel=0
05-07 11:47:12.129 26915 26915 D ViewRootImpl@16a1d05[MainActivity]: mThreadedRenderer.initialize() mSurface={isValid=true 0xb400007bb49d1930} hwInitialized=true
05-07 11:47:12.132 26915 26915 D ViewRootImpl@16a1d05[MainActivity]: reportNextDraw android.view.ViewRootImpl.performTraversals:4658 android.view.ViewRootImpl.doTraversal:3239 android.view.ViewRootImpl$TraversalRunnable.run:11197 android.view.Choreographer$CallbackRecord.run:1650 android.view.Choreographer$CallbackRecord.run:1659 
05-07 11:47:12.133 26915 26915 D ViewRootImpl@16a1d05[MainActivity]: Setup new sync=wmsSync-ViewRootImpl@16a1d05[MainActivity]#11
05-07 11:47:12.133 26915 26915 D ViewRootImpl@16a1d05[MainActivity]: Creating new active sync group ViewRootImpl@16a1d05[MainActivity]#12
05-07 11:47:12.133 26915 26915 D ViewRootImpl@16a1d05[MainActivity]: registerCallbacksForSync syncBuffer=false
05-07 11:47:12.139 26915 28581 D ViewRootImpl@16a1d05[MainActivity]: Received frameDrawingCallback syncResult=0 frameNum=1.
05-07 11:47:12.139 26915 28581 I ViewRootImpl@16a1d05[MainActivity]: mWNT: t=0xb400007a54995230 mBlastBufferQueue=0xb400007a24990070 fn= 1 caller= android.view.ViewRootImpl$8.onFrameDraw:13614 android.view.ThreadedRenderer$1.onFrameDraw:788 <bottom of call stack> 
05-07 11:47:12.139 26915 28581 D ViewRootImpl@16a1d05[MainActivity]: Setting up sync and frameCommitCallback
05-07 11:47:12.141 26915 28577 I BLASTBufferQueue: [ViewRootImpl@16a1d05[MainActivity]#36](f:0,a:0,s:0) onFrameAvailable the first frame is available
05-07 11:47:12.141 26915 28577 D ViewRootImpl@16a1d05[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
05-07 11:47:12.142 26915 28577 D OpenGLRenderer: CFMS:: SetUp Pid : 26915    Tid : 28577
05-07 11:47:12.142 26915 26915 D ViewRootImpl@16a1d05[MainActivity]: reportDrawFinished
05-07 11:47:12.144 26915 26915 I ViewRootImpl@16a1d05[MainActivity]: registerCallbackForPendingTransactions
05-07 11:47:12.146 26915 28582 I ViewRootImpl@16a1d05[MainActivity]: mWNT: t=0xb400007a54975af0 mBlastBufferQueue=0xb400007a24990070 fn= 2 caller= android.view.ViewRootImpl$6.onFrameDraw:5539 android.view.ViewRootImpl$2.onFrameDraw:2103 android.view.ThreadedRenderer$1.onFrameDraw:788 
05-07 11:47:12.174 26915 26915 I ViewRootImpl@52b934d[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 0
05-07 11:47:12.207 26915 26915 I ViewRootImpl@16a1d05[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 0
05-07 11:47:12.207 26915 26915 D ViewRootImpl@16a1d05[MainActivity]: mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400007bb49d1930}
05-07 11:47:12.208 26915 26915 D InputMethodManagerUtils: startInputInner - Id : 0
05-07 11:47:12.208 26915 26915 I InputMethodManager: startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
05-07 11:47:12.241 26915 26915 D InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=false, type=8
05-07 11:47:12.764 26915 26915 I ViewRootImpl@16a1d05[MainActivity]: ViewPostIme pointer 0
05-07 11:47:12.843 26915 26915 I ViewRootImpl@16a1d05[MainActivity]: ViewPostIme pointer 1
05-07 11:47:12.862 26915 26915 E PluginAdapter: Failed to open Rowdy settings: java.lang.IllegalStateException: FragmentManager has been destroyed
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1666)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:507)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at com.RowdyAvocado.RowdyPlugin$load$1.invoke(RowdyPlugin.kt:98)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at com.RowdyAvocado.RowdyPlugin$load$1.invoke(RowdyPlugin.kt:96)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at com.lagradost.cloudstream3.ui.settings.extensions.PluginDetailsFragment.onViewCreated$lambda$3$lambda$1(PluginDetailsFragment.kt:119)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at com.lagradost.cloudstream3.ui.settings.extensions.PluginDetailsFragment.$r8$lambda$3T3wgbWA2GUa2d5VuGxghYXHXVM(Unknown Source:0)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at com.lagradost.cloudstream3.ui.settings.extensions.PluginDetailsFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:6)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at android.view.View.performClick(View.java:8043)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at android.view.View.performClickInternal(View.java:8020)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at android.view.View$PerformClick.run(View.java:31850)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at android.os.Handler.handleCallback(Handler.java:958)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at android.os.Looper.loopOnce(Looper.java:230)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at android.os.Looper.loop(Looper.java:319)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at android.app.ActivityThread.main(ActivityThread.java:8893)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at java.lang.reflect.Method.invoke(Native Method)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
05-07 11:47:12.862 26915 26915 E PluginAdapter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
05-07 11:47:14.065 26915 26915 I ViewRootImpl@16a1d05[MainActivity]: ViewPostIme pointer 0
05-07 11:47:14.143 26915 26915 I ViewRootImpl@16a1d05[MainActivity]: ViewPostIme pointer 1
05-07 11:47:14.150 26915 26915 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=com.google.android.material.motion.MaterialBackOrchestrator$Api34BackCallbackDelegate$1@363e7bd
05-07 11:47:14.162 26915 26915 I ViewRootImpl@16a1d05[MainActivity]: dispatchDetachedFromWindow
05-07 11:47:14.176 26915 26915 D InputTransport: Input channel destroyed: '8c09548', fd=145
05-07 11:47:14.178 26915 26915 D InsetsController: onStateChanged: host=com.lagradost.cloudstream3.prerelease/com.lagradost.cloudstream3.MainActivity from=android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:7085 state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2316), mDisplayCutout=DisplayCutout{insets=Rect(0, 75 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(512, 0 - 568, 75), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2316 physicalDisplayWidth=1080 physicalDisplayHeight=2316 density={2.8125} cutoutSpec={M 0,0 H -10 V 26.66666666666667 H 10 V 0 H 0 Z @dp} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=8, center=Point(8, 8)}, RoundedCorner{position=TopRight, radius=8, center=Point(1072, 8)}, RoundedCorner{position=BottomRight, radius=8, center=Point(1072, 2308)}, RoundedCorner{position=BottomLeft, radius=8, center=Point(8, 2308)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2316), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(956, 0 - 1080, 75) rotation=0}, mDisplayShape=DisplayShape{ spec=1667685767 displayWidth=1440 displayHeight=3088 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {a1a30001 mType=navigationBars mFrame=[0,2181][1080,2316] mVisible=true mFlags=[]}, InsetsSource: {a1a30004 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {a1a30005 mType=mandatorySystemGestures mFrame=[0,2181][1080,2316] mVisible=true mFlags=[]}, InsetsSource: {a1a30006 mType=tappableElement mFrame=[0,2181][1080,2316] mVisible=true mFlags=[]}, InsetsSource: {a1a30024 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {27 mType=displayCutout mFrame=[0,0][1080,75] mVisible=true mFlags=[]}, InsetsSource: {70410000 mType=statusBars mFrame=[0,0][1080,75] mVisible=true mFlags=[]}, InsetsSource: {70410005 mType=mandatorySystemGestures mFrame=[0,0][1080,109] mVisible=true mFlags=[]}, InsetsSource: {70410006 mType=tappableElement mFrame=[0,0][1080,75] mVisible=true mFlags=[]} }
05-07 11:47:14.178 26915 26915 D InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=true, type=1
05-07 11:47:14.179 26915 26915 D InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=true, type=2
05-07 11:47:14.211 26915 26915 I ViewRootImpl@52b934d[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 0
05-07 11:47:14.212 26915 26915 D ViewRootImpl@52b934d[MainActivity]: mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400007bb49fe480}
05-07 11:47:14.213 26915 26915 D InputMethodManagerUtils: startInputInner - Id : 0
05-07 11:47:14.213 26915 26915 I InputMethodManager: startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
05-07 11:47:14.230 26915 26915 D InsetsSourceConsumer: applyRequestedVisibilityToControl: visible=false, type=8
05-07 11:47:15.388 26915 26915 I ImeTracker: com.lagradost.cloudstream3.prerelease:29935f77: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
05-07 11:47:15.388 26915 26915 I InputMethodManager_LC: hsifw() - flag : 0
05-07 11:47:15.388 26915 26915 I InputMethodManager_LC: hsifw() - mService.hideSoftInput
05-07 11:47:15.403 26915 26915 D AnimatorSet: mReversing is false. Don't call initChildren.
05-07 11:47:16.359 26915 26915 I ImeTracker: com.lagradost.cloudstream3.prerelease:b0bdc2b3: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
05-07 11:47:16.359 26915 26915 I InputMethodManager_LC: hsifw() - flag : 0
05-07 11:47:16.360 26915 26915 I InputMethodManager_LC: hsifw() - mService.hideSoftInput
05-07 11:47:16.368 26915 26915 D ScrollView: initGoToTop
05-07 11:47:16.382 26915 26915 D ScrollView:  onsize change changed 
05-07 11:47:17.633 26915 26915 I ViewRootImpl@52b934d[MainActivity]: ViewPostIme pointer 0
05-07 11:47:17.695 26915 26915 I ViewRootImpl@52b934d[MainActivity]: ViewPostIme pointer 1
05-07 11:47:17.712 26915 26915 I ImeTracker: com.lagradost.cloudstream3.prerelease:5a4c026d: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
05-07 11:47:17.712 26915 26915 I InputMethodManager_LC: hsifw() - flag : 0
05-07 11:47:17.712 26915 26915 I InputMethodManager_LC: hsifw() - mService.hideSoftInput
05-07 11:47:18.416 26915 26915 I ViewRootImpl@52b934d[MainActivity]: ViewPostIme pointer 0
05-07 11:47:18.532 26915 26915 I ViewRootImpl@52b934d[MainActivity]: ViewPostIme pointer 1
05-07 11:47:19.399 26915 26915 I ViewRootImpl@52b934d[MainActivity]: ViewPostIme pointer 0
05-07 11:47:19.462 26915 26915 I ViewRootImpl@52b934d[MainActivity]: ViewPostIme pointer 1
05-07 11:47:19.481 26915 26915 D ScrollView: initGoToTop
05-07 11:47:19.492 26915 26915 I Dialog  : mIsDeviceDefault = false, mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
05-07 11:47:19.494 26915 26915 I DecorView: setWindowBackground: isPopOver=false color=ff010102 d=android.graphics.drawable.InsetDrawable@d017b21
05-07 11:47:19.501 26915 26915 D ScrollView: initGoToTop
05-07 11:47:19.506 26915 28577 D NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
05-07 11:47:19.523 26915 26915 D InsetsController: onStateChanged: host=com.lagradost.cloudstream3.prerelease/com.lagradost.cloudstream3.MainActivity from=android.view.ViewRootImpl.setView:1717 state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2316), mDisplayCutout=DisplayCutout{insets=Rect(0, 75 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(512, 0 - 568, 75), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2316 physicalDisplayWidth=1080 physicalDisplayHeight=2316 density={2.8125} cutoutSpec={M 0,0 H -10 V 26.66666666666667 H 10 V 0 H 0 Z @dp} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=8, center=Point(8, 8)}, RoundedCorner{position=TopRight, radius=8, center=Point(1072, 8)}, RoundedCorner{position=BottomRight, radius=8, center=Point(1072, 2308)}, RoundedCorner{position=BottomLeft, radius=8, center=Point(8, 2308)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2316), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(956, 0 - 1080, 75) rotation=0}, mDisplayShape=DisplayShape{ spec=1667685767 displayWidth=1440 displayHeight=3088 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {a1a30001 mType=navigationBars mFrame=[0,2181][1080,2316] mVisible=true mFlags=[]}, InsetsSource: {a1a30004 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {a1a30005 mType=mandatorySystemGestures mFrame=[0,2181][1080,2316] mVisible=true mFlags=[]}, InsetsSource: {a1a30006 mType=tappableElement mFrame=[0,2181][1080,2316] mVisible=true mFlags=[]}, InsetsSource: {a1a30024 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {27 mType=displayCutout mFrame=[0,0][1080,75] mVisible=true mFlags=[]}, InsetsSource: {70410000 mType=statusBars mFrame=[0,0][1080,75] mVisible=true mFlags=[]}, InsetsSource: {70410005 mType=mandatorySystemGestures mFrame=[0,0][1080,109] mVisible=true mFlags=[]}, InsetsSource: {70410006 mType=tappableElement mFrame=[0,0][1080,75] mVisible=true mFlags=[]} }
05-07 11:47:19.523 26915 26915 I ViewRootImpl@c5b71f6[MainActivity]: synced displayState. AttachInfo displayState=2
05-07 11:47:19.525 26915 26915 I ViewRootImpl@c5b71f6[MainActivity]: setView = com.android.internal.policy.DecorView@7a62cd TM=true
```

**Comment by rushi-chavan** [comment]
Thanks for letting me know. Latest update (https://github.com/rushi-chavan/rowdy-cs-extensions/commit/85af6c15f07356b73ad50e4fdf9cb6b3c737fdc0) has fixed this issue

**Comment by Luna712** [comment]
@rushi-chavan thanks but after update to v19 it still happens it worked once and then it stopped again.
